version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - /var/www/docker-study.loc/article-02/html:/var/www/myapp
      - /var/www/docker-study.loc/article-02/docker/site.conf:/etc/nginx/conf.d/site.conf
